# Git abbreviations
abbr -a -- gs 'git status -sb'
abbr -a -- ga 'git add'
abbr -a -- gaa 'git add --all'
abbr -a -- gd 'git diff'
abbr -a -- gds 'git diff --staged'
abbr -a -- gl 'git log --oneline --graph --decorate'
abbr -a -- gll 'git pull'
abbr -a -- gb 'git branch'
abbr -a -- gco 'git checkout'
abbr -a -- gsw 'git switch'
abbr -a -- gr 'git rebase'
abbr -a -- gri 'git rebase -i'
abbr -a -- grom 'git rebase origin/main'
abbr -a -- gpl 'git pull --ff-only'
abbr -a -- gp 'git push'
abbr -a -- gpf 'git push --force-with-lease'
abbr -a -- gpfl 'git add --all && git push --force-with-lease'
abbr -a -- gc 'git commit'
